---
allowVolumeExpansion: true
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: files-dynamic-volumes
provisioner: csi.nutanix.com
parameters:
   csi.storage.k8s.io/node-publish-secret-name: pe-files-secret
   csi.storage.k8s.io/node-publish-secret-namespace: ntnx-system
   csi.storage.k8s.io/controller-expand-secret-name: pe-files-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: ntnx-system
   dynamicProv: ENABLED
   nfsServerName: labFS
   csi.storage.k8s.io/provisioner-secret-name: pe-files-secret
   csi.storage.k8s.io/provisioner-secret-namespace: ntnx-system
   storageType: NutanixFiles
   squashType: root-squash
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4


10.38.207.7:9440:admin:nx2Tech508!
