apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

images:
  - name: registry.k8s.io/metrics-server/metrics-server:v0.8.0
    newName: docker.io/chainguard/metrics-server
    newTag: v0.8.0